language: shell
os: linux
dist: focal
jobs:
  include:
    - stage: docker-compose config file integrity check
      script: docker-compose -f docker-compose.yml -f docker-compose.override.yml config
